### ISSUE TITLE
BRIDE menu missing in eclipse

### ISSUE THREAD

**Issue by SimonEbner** [ipa320/bride#82]
Since I updated the sourcecode today the BRIDE menu is missing in the menu bar so I'm unable to generate code from my models (screenshot below). I tried it both ways, upgrading a previous version and reinstalling bride from scratch. In both cases I made sure, that the ROS_PACKAGE_PATH was set properly.
![screenshot from 2014-07-07 17 12 56](https://cloud.githubusercontent.com/assets/570249/3497233/c89f34e8-05e9-11e4-80c5-8e15fb14804d.png)

**Comment by abubeck** [comment]
The reason for this is the update to Luna in the develop branch. Luna requires a minimum version of java 7 (openjdk-7). Ubuntu 12.04 ships with both openjdk-6 and openjdk-7. Unfortunally ROS installs the package default-jdk with in 12.04 resolves to openjdk-6. (on >12.04 it resolves to openjdk-7-jdk)
The workaround for now is to manually install java7 or java8, e.g. by apt-get install openjdk-7-jdk.
@ipa-fmw : should we try to update the rosdep info to also support java7? As I said, this problem is 12.04 only.

**Comment by floweisshardt** [comment]
is it possible to install openjdk-6 and openjdk-7 at the same time?

**Comment by abubeck** [comment]
yes you can install both in parallel

**Comment by floweisshardt** [comment]
in that case, we can update rosdep with java7.

**Comment by JacqueCC** [comment]
I had the same problem. I installed bride (sudo apt-get install ros-hydro-bride) and it didn't appear in the menu bar. Does anyone know how I can find the problem?

**Comment by JacqueCC** [comment]
When I follow these steps: https://github.com/ipa320/bride/wiki/Developer-setup
I have error by the packages: 
org.ros.model.ros
org.ros.model.ros_package.diagram
org.ros.model.ros.diagram

I had created the Bride Development but it's not possible to run that without error.
I can not go further.
I am not sure if I am doing this right because I installed Bride and didn't appear BRIDE in the menu bar. Then i found this link and followed with these steps.
When I press the button Run->Bride Development, then it show an error, I press to proceed anyway and it opens another eclipse window with BRIDE in the menu bar and it is with error by these three packages yet.
What am I doing wrong?
Thanks in advance

**Comment by abubeck** [comment]
@JacqueCC : please use a java version >6 when using the developer version as stated above. The released version still works with java 6.

**Comment by abubeck** [comment]
@JacqueCC : The errors are resolved when you regenerate the metamodels. This is explained in the lower part of the developer setup.

**Comment by JacqueCC** [comment]
Actually I installed openjdk-7-jdk... I will try to solve the problem finding these metamodels and  regenerating them.
Thank you @abubeck

**Comment by abubeck** [comment]
@JacqueCC : You can check with "java -version" what you are using to run bride. Maybe you have multiple versions installed. If this is the case you can use "sudo update-alternatives --config java" to choose the right one.

**Comment by JacqueCC** [comment]
@abubeck : I am a little confused. I have installed openjdk-7-jdk because with openjdk-6-jdk it wasn't working. But it still not working... Now I was thinking about, that I did like the tutorial says, I installed bride using "sudo apt-get install ros-hydro-bride", but I am using groovy environment. Is it not a problem? I founded this: https://github.com/ipa320/bride/wiki/Installation-of-nightly-builds
I will try to use "sudo update-alternatives --config java" to choose the right java version.
Thank you
